; Taille maximale d'un fichier envoyé
upload_max_filesize = 32M

; Taille maximale de toute la requête POST
post_max_size = 32M

; Mémoire disponible pour PHP
memory_limit = 256M

; Temps maximum d'exécution d'un script
max_execution_time = 120

; Temps maximum autorisé pour l'envoi des fichiers
max_input_time = 120